name: Atualizar config.json

on:
  push:
    paths:
      - 'comum/**/*.sql'
  pull_request:
    paths:
      - 'comum/**/*.sql'

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install @actions/github

      - name: Atualizar config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/updateConfig.js

      - name: Commit e Push das mudanças
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add config.json
          git commit -m "Atualização automática do config.json" || exit 0
          git push origin HEAD:${{ github.ref_name }}
